/** Kolom template import karyawan. `*` = wajib. */
export const IMPORT_COLUMNS: { key: string; label: string; contoh: string | number }[] = [
  { key: "nama", label: "nama*", contoh: "Budi Santoso" },
  { key: "no_ktp", label: "no_ktp", contoh: "6474010101900001" },
  { key: "jenis_kelamin", label: "jenis_kelamin (L/P)", contoh: "L" },
  { key: "tempat_lahir", label: "tempat_lahir", contoh: "Bontang" },
  { key: "tanggal_lahir", label: "tanggal_lahir (DD/MM/YYYY)", contoh: "01/01/1990" },
  { key: "alamat_ktp", label: "alamat_ktp", contoh: "Jl. Contoh No. 1" },
  { key: "alamat_domisili", label: "alamat_domisili", contoh: "Mess Blok A" },
  { key: "no_hp", label: "no_hp", contoh: "081234567890" },
  { key: "email", label: "email", contoh: "" },
  { key: "tanggal_masuk", label: "tanggal_masuk* (DD/MM/YYYY)", contoh: "01/10/2026" },
  { key: "jenis_kontrak", label: "jenis_kontrak (PKWT/Harian)", contoh: "PKWT" },
  { key: "no_kontrak", label: "no_kontrak", contoh: "PKWT/001/2026" },
  { key: "tanggal_akhir_kontrak", label: "tanggal_akhir_kontrak (DD/MM/YYYY)", contoh: "30/09/2027" },
  { key: "kode_klasifikasi", label: "kode_klasifikasi", contoh: "WLD6G" },
  { key: "area", label: "area", contoh: "Piping" },
  { key: "regu", label: "regu", contoh: "Regu A" },
  { key: "basis_gaji", label: "basis_gaji (bulanan/harian)", contoh: "bulanan" },
  { key: "gaji_pokok", label: "gaji_pokok", contoh: 5000000 },
  { key: "tunjangan_tetap", label: "tunjangan_tetap (per bulan)", contoh: 0 },
  { key: "tunjangan_makan_harian", label: "tunjangan_makan_harian (tidak tetap)", contoh: 0 },
  { key: "tunjangan_transport_harian", label: "tunjangan_transport_harian (tidak tetap)", contoh: 0 },
  { key: "bank", label: "bank", contoh: "BRI" },
  { key: "no_rekening", label: "no_rekening", contoh: "0123456789" },
  { key: "nama_rekening", label: "nama_rekening", contoh: "Budi Santoso" },
  { key: "npwp", label: "npwp", contoh: "" },
  { key: "status_ptkp", label: "status_ptkp", contoh: "K/1" },
  { key: "no_bpjs_kesehatan", label: "no_bpjs_kesehatan", contoh: "" },
  { key: "no_bpjs_ketenagakerjaan", label: "no_bpjs_ketenagakerjaan", contoh: "" },
  { key: "ukuran_baju", label: "ukuran_baju", contoh: "L" },
  { key: "ukuran_sepatu", label: "ukuran_sepatu", contoh: "42" },
];
